# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17f67b29e1fc448678d7a6ba484a4b9fa023aecddf68e26f7d74f2e01c91123d696f04599bd797061b40cec6eeebdf7582ecd17eff229ddd5d00fe38e8e0dc96

test:
  secret_key_base: f78943856bd6e04c6786bd95b73cd4bf0c95c77a290b465daf591882e1e7d1c1f1401d3364dcd5fdec54879c71ec641af6c811ca766c5760c1565c9a201e4649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
